# Generated by Django 3.2.9 on 2022-03-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=12)),
                ('Last_Name', models.CharField(max_length=12)),
                ('User_Name', models.CharField(max_length=12)),
                ('Mobile_Number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=8)),
                ('Confirm_Password', models.CharField(max_length=8)),
            ],
        ),
    ]
