# Generated by Django 3.2.9 on 2022-03-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Confirm_Password',
        ),
    ]
